version: '3.3'
services:
  backend1:
    image: polarlightning/bitcoind:23.0
    container_name: polar-n2-backend1
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: backend1
    command: >-
      bitcoind -server=1 -regtest=1
      -rpcauth=polaruser:5e5e98c21f5c814568f8b55d83b23c1c$$066b03f92df30b11de8e4b1b1cd5b1b4281aa25205bd57df9be82caf97a05526
      -debug=1 -zmqpubrawblock=tcp://0.0.0.0:28334
      -zmqpubrawtx=tcp://0.0.0.0:28335 -zmqpubhashblock=tcp://0.0.0.0:28336
      -txindex=1 -dnsseed=0 -upnp=0 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0
      -rpcport=18443 -rest -listen=1 -listenonion=0 -fallbackfee=0.0002
      -blockfilterindex=1 -peerblockfilters=1
    volumes:
      - /Users/andrew/.polar/networks/2/volumes/bitcoind/backend1:/home/bitcoin/.bitcoin
    expose:
      - '18443'
      - '18444'
      - '28334'
      - '28335'
    ports:
      - '18443:18443'
      - '19444:18444'
      - '28334:28334'
      - '29335:28335'
  alice:
    image: lnd-master:latest
    container_name: polar-n2-alice
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: alice
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=alice --externalip=alice
      --tlsextradomain=alice --tlsextradomain=polar-n2-alice
      --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080
      --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=polar-n2-backend1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://polar-n2-backend1:28334
      --bitcoind.zmqpubrawtx=tcp://polar-n2-backend1:28335 --accept-amp
      --accept-keysend
    restart: always
    volumes:
      - /Users/andrew/.polar/networks/2/volumes/lnd/alice:/home/lnd/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8081:8080'
      - '10001:10009'
      - '9735:9735'
  bob:
    image: lnd-master:latest
    container_name: polar-n2-bob
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: bob
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=bob --externalip=bob
      --tlsextradomain=bob --tlsextradomain=polar-n2-bob --listen=0.0.0.0:9735
      --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active
      --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=polar-n2-backend1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://polar-n2-backend1:28334
      --bitcoind.zmqpubrawtx=tcp://polar-n2-backend1:28335 --accept-amp
      --accept-keysend
    restart: always
    volumes:
      - /Users/andrew/.polar/networks/2/volumes/lnd/bob:/home/lnd/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8082:8080'
      - '10002:10009'
      - '9736:9735'

  alice-taro:
    image: taro-master:latest
    container_name: polar-n2-alice-taro
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: alice-taro
    # command: >-
    #   tarod --network=regtest --debuglevel=debug
    #   --lnd.macaroonpath=/home/lnd/.lnd/data/chain/bitcoin/regtest/admin.macaroon 
    #   --lnd.tlspath=/home/lnd/.lnd/tls.cert
    #   --tarodir=~/.taro 
    #   --rpclisten=0.0.0.0:10029 
    #   --restlisten=0.0.0.0:8089
    #   —-lnd.host=tcp://polar-n2-alice:10001
    stdin_open: true # docker run -i
    tty: true  
    command: "/bin/bash"
    volumes:
      - /Users/andrew/.polar/networks/2/volumes/lnd/alice:/home/lnd/.lnd
      - /Users/andrew/.polar/networks/2/volumes/taro/alice:/home/taro/.taro
    expose:
      - '8089'
      - '10029'
    ports:
      - '8089:8089'
      - '10029:10029'
    depends_on:
      - 'alice'
      - 'backend1'
    restart: always
